import Framer from './framer_components/Framer.js';
import { FramerComponent } from './framer_components/Framer.js';
export default class HomePage extends FramerComponent {
    constructor() {
        super(...arguments);
        this.props = {};
    }
    init() {
        this.className = "HomePage";
        this.append(Framer.createElement("div", { className: "cover" },
            Framer.createElement("img", { src: "./assets/circuits.svg", alt: "circuit", className: "circuit" }),
            Framer.createElement("div", { className: "center" },
                Framer.createElement("img", { src: "./assets/logo.svg", alt: "SecOps Partners' Logo", className: "logo" }),
                Framer.createElement("h1", null,
                    Framer.createElement("span", { className: "blue heavy" }, "SecOps"),
                    " ",
                    Framer.createElement("span", { className: "red normal" }, "Partners")),
                Framer.createElement("h2", { className: "normal" }, "Experts in security operations")),
            Framer.createElement("img", { src: "./assets/circuits.svg", alt: "circuit", className: "circuit" })), Framer.createElement("div", { className: "fill-vertical cut-corner gst" },
            Framer.createElement("h1", { className: "red" }, "Modern problems"),
            Framer.createElement("div", { className: "gr3" },
                Framer.createElement("div", { className: "grid-top" },
                    Framer.createElement("p", null, "As organizations are pressured to expand their cloud operations, they face new major security issues that they are not properly prepared for. Upon facing these challenges, organizations often turn to implementing several different security management approaches. However, unfortunately, they shortly come to the reality that their approaches are too scattered and not nearly effective enough.")),
                Framer.createElement("div", { className: "grid-center" },
                    Framer.createElement("p", { className: "red heavy" }, "The end results are always the same:"),
                    Framer.createElement("div", { className: "gc2" },
                        Framer.createElement("div", null,
                            Framer.createElement("ul", null,
                                Framer.createElement("li", null,
                                    Framer.createElement("span", { className: "blue heavy" }, "Scattered management"),
                                    " of security vulnerabilities and incidents across multiple tools or even spreadsheets lead to a ",
                                    Framer.createElement("span", { className: "blue heavy" }, "lack of easily accessible data.")),
                                Framer.createElement("li", null,
                                    "Security analysts ",
                                    Framer.createElement("span", { className: "blue heavy" }, "start from scratch"),
                                    " when investigating every issue, ",
                                    Framer.createElement("span", { className: "blue heavy" }, "delaying response time and increasing manual work.")))),
                        Framer.createElement("img", { src: "./assets/cloud-lock.png", alt: "secure cloud", className: "img-fill-space" }))),
                Framer.createElement("div", { className: "grid-bottom" },
                    Framer.createElement("p", null,
                        "To make matters worse, it is said that around ",
                        Framer.createElement("span", { className: "blue heavy" }, "80% of cyberattacks"),
                        " exploit known vulnerabilities. ",
                        Framer.createElement("span", { className: "red heavy" }, "Organizations need an efficient, streamlined, process to prevent iminent cyberattacks and respond to vulnerabilities quicker."))))), Framer.createElement("div", { className: "fill-vertical cut-corner gst" },
            Framer.createElement("h1", { className: "blue" }, "We have the solutions"),
            Framer.createElement("div", { className: "gr3" },
                Framer.createElement("div", { className: "grid-top" },
                    Framer.createElement("p", null, "The Security Operations Management (SOM) suite in ServiceNOW is a better way to get the visibility you need to thwart attacks and respond quicker.  Teams need to gain better visibility into their entire security posture and minimize time invested in manual processes.  Security Operations provides a single platform for responding to incidents and vulnerabilities and can enrich incidents with threat intelligence to further expedite response.")),
                Framer.createElement("div", { className: "grid-center" },
                    Framer.createElement("p", null,
                        "We can ",
                        Framer.createElement("span", { className: "red heavy" }, "eliminate inefficient processes"),
                        " by combining security, IT, and risk capabilities into an ",
                        Framer.createElement("span", { className: "red heavy" }, "integrated risk platform"),
                        " inside of ServiceNow."),
                    Framer.createElement("p", { className: "blue heavy" }, "Inside of ServiceNow we can leverage effective automation and organization to: "),
                    Framer.createElement("div", { className: "gc2" },
                        Framer.createElement("ul", null,
                            Framer.createElement("li", null,
                                Framer.createElement("span", { className: "red heavy" }, "Reduce time"),
                                " spent on basic, repetitive, tasks."),
                            Framer.createElement("li", null,
                                Framer.createElement("span", { className: "red heavy" }, "Quickly"),
                                " identify, prioritize, and remediate changes that affect security and risk postures."),
                            Framer.createElement("li", null,
                                Framer.createElement("span", { className: "red heavy" }, "Track"),
                                " security with ",
                                Framer.createElement("span", { className: "red heavy" }, "advanced dashboards and reporting.")),
                            Framer.createElement("li", null,
                                Framer.createElement("span", { className: "red heavy" }, "Enhance"),
                                " your view of your security posture.")),
                        Framer.createElement("img", { src: "./assets/chart.jpg", alt: "chart", className: "img-fill-space" }))),
                Framer.createElement("div", { className: "grid-bottom" },
                    Framer.createElement("p", null, "Prioritize and remediate vulnerabilities and security incidents faster. Unify data and processes across IT, security, and risk teams."),
                    Framer.createElement("p", null, "Your organization faces modern cloud integration problems daily, we have the solutions.")))));
    }
}
